[package]
name = "exit_node"
version = "0.1.0"
edition = "2024"

[dependencies]
shared = { path = "../shared" }
tokio = { version = "1", features = ["full"] }
serde_json = "1"
anyhow = "1"
base64 = "0.21"
rsa = "0.9"
