[package]
name = "shared"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rand = "0.8"
aes-gcm = "0.10"
aes = "0.8"
rsa = "0.9"
sha2 = "0.10"
base64 = "0.21"
once_cell = "1"
